import Foundation

// Writes `docs/themes.js` — the website's copy of Driftwood's built-in
// palettes — from `TerminalTheme.builtIn` itself.
//
// The site re-creates the panel in HTML and CSS, so it needs every color the
// app paints. Hand-copying them is what `Tools/make-icon.swift` does for the
// four icon colors, and that copy is already a coupling nothing enforces: edit
// `driftwoodNight` and the icon does not follow. Four themes × 21 roles is far
// past the size where that stays honest, so this reads the source of truth
// instead. `make check` diffs the checked-in file against a fresh run and
// fails when they differ, which is what makes the generated file trustworthy
// rather than merely convenient.
//
// This is possible only because `TerminalTheme` is Foundation-only. It is the
// same property that lets `Checks/main.swift` import it, and the reason this
// script compiles against the real type rather than a transcription of it.
//
// Output is byte-identical across runs — no dictionary iteration, no
// timestamp, no build path — so `make site` with no source change leaves the
// tree clean, matching `make icon`.
//
// Usage: make-site-themes <output-path> <version>

@main
struct MakeSiteThemes {
    static func main() {
        let arguments = CommandLine.arguments
        guard arguments.count == 3 else {
            FileHandle.standardError.write(
                Data("usage: make-site-themes <output-path> <version>\n".utf8))
            exit(2)
        }
        let outputPath = arguments[1]
        let version = arguments[2]

        var out = header(version: version)
        out += "window.DRIFTWOOD_VERSION = \(quote(version));\n\n"
        out += "window.DRIFTWOOD_THEMES = [\n"
        out += TerminalTheme.builtIn.map(entry).joined(separator: ",\n")
        out += "\n];\n"

        do {
            try out.write(toFile: outputPath, atomically: true, encoding: .utf8)
        } catch {
            FileHandle.standardError.write(
                Data("make-site-themes: cannot write \(outputPath): \(error)\n".utf8))
            exit(1)
        }
        print("wrote \(outputPath) — \(TerminalTheme.builtIn.count) themes")
    }

    /// The banner says which file to edit instead, because the obvious
    /// response to a wrong color on the site is to fix it where it is wrong.
    private static func header(version: String) -> String {
        """
        // Generated by `make site` from Sources/Driftwood/Terminal/TerminalTheme.swift.
        //
        // Do not edit this file. `make check` regenerates it and fails on any
        // difference, so an edit here is reverted at the next check. To change a
        // color on this site, change the theme in TerminalTheme.swift and run
        // `make site`.
        //
        // Driftwood \(version)


        """
    }

    private static func entry(_ theme: TerminalTheme) -> String {
        let ansi = theme.ansi.map { "      \(quote(hex($0)))" }.joined(separator: ",\n")
        return """
          {
            id: \(quote(theme.id)),
            title: \(quote(theme.title)),
            ansi: [
        \(ansi)
            ],
            background: \(quote(hex(theme.background))),
            foreground: \(quote(hex(theme.foreground))),
            cursor: \(quote(hex(theme.cursor))),
            selection: \(quote(hex(theme.selection))),
            tabBarText: \(quote(hex(theme.tabBarText)))
          }
        """
    }

    /// `#RRGGBB` when opaque, `#RRGGBBAA` otherwise — the same two shapes
    /// `TerminalTheme.parseHex` accepts in `config.json`, so a value copied off
    /// the site into a custom theme parses. CSS reads `#RRGGBBAA` natively, so
    /// the alpha needs no separate channel.
    private static func hex(_ color: TerminalTheme.RGBA) -> String {
        let rgb = String(format: "#%02x%02x%02x", color.r, color.g, color.b)
        return color.a == 255 ? rgb : rgb + String(format: "%02x", color.a)
    }

    /// Theme ids and titles are Swift string literals in this repo, not user
    /// input, but they land in a JS file that a browser executes. Escaping is
    /// one line and the alternative is a syntax error at best.
    private static func quote(_ value: String) -> String {
        var escaped = ""
        for character in value.unicodeScalars {
            switch character {
            case "\"": escaped += "\\\""
            case "\\": escaped += "\\\\"
            case "\n": escaped += "\\n"
            case "\r": escaped += "\\r"
            case "\u{2028}": escaped += "\\u2028"   // JS line separator
            case "\u{2029}": escaped += "\\u2029"
            default: escaped.unicodeScalars.append(character)
            }
        }
        return "\"\(escaped)\""
    }
}
